5.4
laravel-china/laravel-docs pull request #135
Opened 2017-02-13 15:38 UTC by cmzz

views.md
helpers.md

2个文档翻译完了，请审阅。

ps: 由于刚刚 pr  的分支是 5.3， 说以重新申请了一次 pr 到5.4分支。

2017-02-13 16:21 UTC, milkmeowo commented
@cmzz 请先解决冲突

2017-02-13 16:33 UTC, cmzz commented
冲突？ 好想并没有哎

2017-02-14 01:40 UTC, milkmeowo commented
![image](https://cloud.githubusercontent.com/assets/22437128/22911192/70f5fb88-f299-11e6-96a1-6fab79e1af91.png)


注意 PR 的提示 `This branch has conflicts that must be resolved`，我 diff 了一下，发现你应该是基于英文原版来翻译的，但可能翻译出来之后会和本仓库 5.4 分支某些地方产生冲突， 你可以在本地先 pull 一下来发现问题解决冲突，也可以直接点击 PR 下面的 `Resolve conflict` 按钮解决一下冲突

![image](https://cloud.githubusercontent.com/assets/22437128/22911098/f9fc6684-f298-11e6-9240-ef929924e513.png)


![image](https://cloud.githubusercontent.com/assets/22437128/22911172/54fa1090-f299-11e6-9850-a89f6697c719.png)

2017-02-14 02:11 UTC, cmzz commented
挺奇怪的， 我 fork 后的项目里面并没有 5.4 的分支。 我删除再重新fork 一下看看

2017-02-14 02:44 UTC, cmzz commented
@milkmeowo 好了，不太会操作😝

2017-02-14 03:01 UTC, milkmeowo commented
@cmzz 如果提 PR 一般都需要先同步上游的仓库，解决好冲突，再提交PR。

因为可能在你 fork 下来直到你完成某个功能想提 PR 的期间，可能有一大堆人在疯狂 commit，所以就会产生冲突了

2017-02-14 03:31 UTC, milkmeowo commented
开始第一次 review

2017-02-14 04:18 UTC, milkmeowo requested changes
请按要求修改，请其他 review 成员查看与 5.3 不同的地方，并给出建议加以讨论

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +# 辅助函数
统一采用给定的标题吧

`辅助函数` --> `Laravel 的辅助函数列表`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +Laravel 包含有各种各样的PHP辅助函数，许多都是在 Laravel 自身框架中使用到。如果你觉得实用，也可以在你自己的应用中使用它们。
中英之间保留空格

`各种各样的PHP辅助函数` --> `各种各样的 PHP 辅助函数`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> -[secure_url](#method-secure-url)
少了` [secure_url](#method-secure-url)`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> -[cache](#method-cache)
少了 `[cache](#method-cache)`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +[retry](#method-retry)
不要随意修改顺序，请放回原位

`L:126` --> `L:132`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +    $array = ['products' => ['desk' => ['price' => 100]]];
代码示例不要修改

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +    $hasDesk = array_has($array, 'products.desk');
代码示例不要修改

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> -
代码示例不要遗漏

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +    return is_string($value);
注意代码格式，少了 4 个空格

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +`mix` 函数获取带有版本号的 [versioned mix file](/docs/{{version}}/mix):
`mix` 函数获取带有版本号的 [versioned mix file](/docs/{{version}}/mix):

-->

`mix` 函数获取带有版本号的 [mix](/docs/{{version}}/mix) 文件:

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> -
漏了翻译

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +`trans_choice` 函数根据数量翻译指定的语句：
[Breaking Change] 这句我建议这样修改

`trans_choice` 函数根据数量翻译指定的语句：

-->

`trans_choice` 函数根据给定数量来决定翻译指定语句的复数形式还是单数形式：

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +	$url = asset('img/photo.jpg');
注意格式，多了几个空格

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +	echo secure_asset('foo/bar.zip', $title, $attributes = []);
注意格式，多了几个空格

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> -
忘记翻译

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +#### `cache()` {#cache-method}
不要修改占位符

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +`event` 函数发派指定的 [事件](/docs/{{version}}/events) 到所属的侦听器：
发派 --> 派发

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +<a name="method-method_field"></a>
不要修改锚点

`method_field` --> `method-field`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +`old` 函数 [获取](/docs/{{version}}/requests#retrieving-input) session 内一次性的旧有输入值：
建议

`一次性的旧有输入值` --> `一次性的历史输入值`

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +  }, 100);
注意代码格式，多了几个空格

2017-02-14 04:18 UTC, milkmeowo commented on helpers.md
> +`method_field` 函数生成模拟表单 HTTP 动词的 HTML 表单隐藏字段。例如，使用 [Blade 语法](/docs/{{version}}/blade)：
模拟表单 HTTP 动词的的 HTML 表单隐藏字段

-->

模拟表单各种 HTTP 动作请求的 HTML 表单隐藏字段

2017-02-14 04:18 UTC, milkmeowo commented on views.md
> +如果需要测试一个视图文件是否存在，你可以使用 `View` Facade 上的 `exists` 方法来判定，如果测试的视图文件存在，则返回值为 `true` ：
如果需要测试一个视图文件是否存在

-->

如果需要判断一个视图文件是否存在

2017-02-14 05:18 UTC, milkmeowo commented on helpers.md
> -
准确来说，示例代码遗漏

2017-02-14 05:19 UTC, milkmeowo commented on helpers.md
> -
准确来说，示例代码遗漏

2017-02-14 09:39 UTC, cmzz commented
已按要求完成修改

2017-02-15 01:52 UTC, milkmeowo reviewed
忘记翻译，其他没什么问题，我直接补全，可以合并

2017-02-15 01:52 UTC, milkmeowo commented on helpers.md
> -
忘记翻译

2017-02-15 01:59 UTC, milkmeowo approved these changes

2017-02-15 01:59 UTC, merged