translate complete
laravel-china/laravel-docs pull request #159
Opened 2017-02-16 18:22 UTC by skyverd

已经完成翻译，请通过PR

2017-02-17 03:41 UTC, oustn commented on database.md
> +默认情况下，Laravel 的 [环境配置](/docs/{{version}}/installation#environment-configuration) 示例会使用 [Laravel Homestead](/docs/{{version}}/homestead)，对于 Laravel 开发来说这是一个相当便利的本地虚拟机。当然你也可以根据需求来随时修改本机端的数据库设置
句子最后的标点符号：“。”

2017-02-17 03:45 UTC, oustn commented on database.md
> +运行一个基础的查询语句, 你可以使用 `DB` facade 的 `select` 方法：
使用全角标点符号“，”

2017-02-17 03:46 UTC, oustn commented on database.md
> +         *在应用用户中查询出已激活的用户列表。
一般注释 的* 跟 注释之间添加一个空格

2017-02-17 03:47 UTC, oustn commented on database.md
> +运行一个基础的查询语句, 你可以使用 `DB` facade 的 `select` 方法：
使用全角标点符号“，”

2017-02-17 03:48 UTC, oustn commented on database.md
> +         *在应用用户中查询出已激活的用户列表。
注释符号* 跟注释内容之间添加一个空格

2017-02-17 03:54 UTC, oustn commented on database.md
> + `select` 方法以数组的形式返回结果集，数组中的每一个结果都是一个PHP `StdClass` 对象,你可以像下面这样访问结果值：
“对象,你可” 使用全角符号

2017-02-17 03:55 UTC, oustn commented on database.md
> +运行 `Insert` 语句, 你可以是使用 `DB` facade 的 `insert` 方法 。 像 `select` 一样， 该方法将原生SQL语句作为第一个参数，将参数绑定作为第二个参数：:
全角标点

2017-02-17 03:55 UTC, oustn commented on database.md
> +运行 `Insert` 语句, 你可以是使用 `DB` facade 的 `insert` 方法 。 像 `select` 一样， 该方法将原生SQL语句作为第一个参数，将参数绑定作为第二个参数：:
全角标点

2017-02-17 03:58 UTC, oustn commented on database.md
Register the service provider. -- 注释未翻译

2017-02-17 04:26 UTC, oustn commented on eloquent-collections.md
> +> {note} 大部分的 Eloquent 集合会返回新的「Eloquent 集合」实例，但是 `pluck`, `keys`, `zip`, `collapse`, `flatten` 和 `flip` 方法会返回 [基础集合](/docs/{{version}}/collections) 实例。
{note} 在官方文档中显示一个图标，laravel china 没有这个功能，应该要删掉

2017-02-17 04:29 UTC, oustn commented on eloquent-mutators.md
> +当某个字段被认为是日期时，你或许想将其数值设置成一个 UNIX 时间戳、日期字符串（`Y-m-d`）、日期时间（ `date-time` ）字符串、当然还有 `DateTime` 或 `Carbon` 实例，然后日期数值将会被自动保存到数据库中：
“字符串、当然还” -- 这个地方用逗号更合适

2017-02-17 05:21 UTC, oustn commented on eloquent-relationships.md
> +你可在 Eloquent 模型类内中，把 Eloquent 关联定义成方法（methods）。因为，关联就像 Eloquent 模型一样，也可以作为强大的 [查询语句构造器](/docs/{{version}}/queries)，定义关联为方法，因为其提供了强而有力的链式调用及查找功能。例如，我们可以在 `posts` 关联的链式调用中附加一个约束条件：
因为其提供了强而有力的链式调用及查找功能 --> 为其提供了强而有力的链式调用及查找功能

2017-02-17 05:22 UTC, oustn commented on eloquent-relationships.md
> +所以，我们可以从 `User` 模型访问到 `Phone` 模型。现在，让我们在 `Phone` 模型上定义一个关联，此关联能够让我们访问拥有此电话的 `User` 模型。我们可以定义与 `hasOne` 关联相对应的 `belongsTo` 方法
句尾缺少冒号

2017-02-17 05:34 UTC, oustn commented on eloquent-relationships.md
> +切记，Eloquent 会自动判断 `Comment` 模型上正确的外键字段。按约定来说，Eloquent 会取用自身模型的名称的「Snake Case」，并在后方加上 `_id`。所以，以此例来说，Eloquent 会假设 `Comment` 模型的外键是 `post_id`。
*建议*
按约定来说，Eloquent 会取用自身模型的名称的「Snake Case」 ->  按约定来说，Eloquent 会取用自身模型名称的「Snake Case(蛇形命名法)」名称

2017-02-17 05:38 UTC, oustn commented on eloquent-relationships.md
> +默认情况下，Laravel 会使用「包含命名空间的类名」作为多态表的类型区分，例如，`Comment` 属于 `Post` 或者 `Video` , `commentable_type ` 的默认值可以分别是 `App\Post` 或者 `App\Video` 。然而，你也许会想使用应用中的内部结构来对数据库进行解耦。在这个例子中，你可以定义一个「多态对照表」来指引 Eloquent 对各个模型
或者 `Video` , `commentable_type ` -> 全角逗号

2017-02-17 05:41 UTC, oustn commented on eloquent-relationships.md
> +例如，假设有一个博客系统，其中 `User` 模型拥有许多关联的 `Post` 模型:
句尾全角冒号

2017-02-17 05:43 UTC, oustn commented on eloquent-relationships.md
> +有时你可能想要在单次操作中预加载多种不同的关联。要这么做，只需传递额外的参数至 `方法` 即可：
只需传递额外的参数至 `方法` 即可 -> 只需传递额外的参数至 `with` 方法 即可：

2017-02-17 05:47 UTC, oustn commented on eloquent-relationships.md
> +如果你想设置预加载查询的额外条件，则可以传递一个键值为你想要的关联的数组至 `load` 方法。这个数组的值应是用于接收查询 `闭包` 实例：
这个数组的值应是用于接收查询 `闭包` 实例 -> 这个数组的值应是用于接收查询实例的 `Closure` 实例

2017-02-17 05:49 UTC, oustn commented on eloquent-relationships.md
> +当删除一个 `belongsTo` 关联时，你可以使用 `dissociate` 方法。此方法会置该关联的外键为空(null)：
外键为空(null)： -> 全角符号，另外有没有必要加一个空格？

2017-02-17 05:50 UTC, summerblue commented on eloquent-collections.md
> +> {note} 大部分的 Eloquent 集合会返回新的「Eloquent 集合」实例，但是 `pluck`, `keys`, `zip`, `collapse`, `flatten` 和 `flip` 方法会返回 [基础集合](/docs/{{version}}/collections) 实例。
这个不用删除哦

2017-02-17 05:54 UTC, oustn commented on eloquent-relationships.md
> -#### Toggling Associations
### Toggling Associations
### Saving Additional Data On A Pivot Table
### Updating A Record On A Pivot Table

这三点是不是漏了？

2017-02-17 05:56 UTC, oustn commented on eloquent-serialization.md
> -> {note} When hiding relationships, use the relationship's method name, not its dynamic property name.
{note} 不用翻译，这是官方自定义的markdown格式

2017-02-17 05:58 UTC, oustn commented on eloquent-serialization.md
> +访问器创建成功后，只需添加该属性到改模型的 `appends` 属性中。注意，属性名称通常遵循 "[Snake Case](https://en.wikipedia.org/wiki/Snake_case)" 的命名方式，即是访问器的名称是基于 "Camel Case" 的命名方式。
“” 应该使用 「」

2017-02-17 06:00 UTC, oustn requested changes
部分标点没有注意使用全角

2017-02-17 06:14 UTC, oustn commented on eloquent-collections.md
> +> {note} 大部分的 Eloquent 集合会返回新的「Eloquent 集合」实例，但是 `pluck`, `keys`, `zip`, `collapse`, `flatten` 和 `flip` 方法会返回 [基础集合](/docs/{{version}}/collections) 实例。
哦哦，只是不用翻译，我以为要删掉 ..

2017-02-19 14:38 UTC, skyverd commented on eloquent-relationships.md
> +切记，Eloquent 会自动判断 `Comment` 模型上正确的外键字段。按约定来说，Eloquent 会取用自身模型的名称的「Snake Case」，并在后方加上 `_id`。所以，以此例来说，Eloquent 会假设 `Comment` 模型的外键是 `post_id`。
此处的「Snake Case(蛇形命名法)」中间的括号应该是 全角的吧？

2017-02-19 14:47 UTC, skyverd commented on eloquent-relationships.md
> +切记，Eloquent 会自动判断 `Comment` 模型上正确的外键字段。按约定来说，Eloquent 会取用自身模型的名称的「Snake Case」，并在后方加上 `_id`。所以，以此例来说，Eloquent 会假设 `Comment` 模型的外键是 `post_id`。
想了想，我觉得还是不用加这个注释，应该都看的懂，包括 Camel Case 这种，5.3里面也没有翻译，建议还是保持不翻译吧

2017-02-19 14:59 UTC, skyverd commented on eloquent-relationships.md
> +如果你想设置预加载查询的额外条件，则可以传递一个键值为你想要的关联的数组至 `load` 方法。这个数组的值应是用于接收查询 `闭包` 实例：
Closure 应该翻译 [https://laravel-china.org/docs/5.4/about#翻译对照列表](https://laravel-china.org/docs/5.4/about#翻译对照列表)

2017-02-19 15:01 UTC, skyverd commented on eloquent-relationships.md
> +当删除一个 `belongsTo` 关联时，你可以使用 `dissociate` 方法。此方法会置该关联的外键为空(null)：
加空格吧

2017-02-19 15:52 UTC, skyverd commented
已修改提交新的PR

2017-02-19 15:52 UTC, closed without merging